name: flutter_piapp
description: "Projeto em Flutter para PI-VA"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  sqflite: ^2.0.0+4  # Para manipulação do banco de dados SQLite
  path_provider: ^2.0.2  # Para localizar o diretório do banco de dados no dispositivo
  logger: ^1.3.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/  # Isso inclui todos os arquivos na pasta 'assets/images/'
