name: lista_puc_go

description: "Projeto em Flutter para PI-VA"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  sqflite: ^2.0.0+4  # Para manipulação do banco de dados SQLite
  path_provider: ^2.0.2  # Para localizar o diretório do banco de dados no dispositivo
  logger: ^1.3.0
  path: ^1.8.3
  mask_text_input_formatter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.10.0  # Verifique se a versão mais recente é compatível

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon_puc.png"
  remove_alpha_ios: true  # Remover a transparência para iOS

flutter:
  uses-material-design: true

  assets:
    - assets/images/  # Inclui todos os arquivos na pasta 'assets/images/'
